CREATE TABLE `audience_contributions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`date` timestamp NOT NULL,
	`tip_amount` varchar(32) DEFAULT '0',
	`tip_fee` varchar(32) DEFAULT '0',
	`tip_score` varchar(32) DEFAULT '0',
	`watch_duration` int DEFAULT 0,
	`valid_watch_duration` int DEFAULT 0,
	`watch_score` varchar(32) DEFAULT '0',
	`chat_count` int DEFAULT 0,
	`valid_chat_count` int DEFAULT 0,
	`chat_score` varchar(32) DEFAULT '0',
	`featured_post_count` int DEFAULT 0,
	`featured_post_score` varchar(32) DEFAULT '0',
	`total_score` varchar(32) DEFAULT '0',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `audience_contributions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `creator_contributions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`stream_id` int,
	`date` timestamp NOT NULL,
	`stream_duration` int DEFAULT 0,
	`valid_stream_duration` int DEFAULT 0,
	`stream_score` varchar(32) DEFAULT '0',
	`avg_ccu` int DEFAULT 0,
	`ccu_score` varchar(32) DEFAULT '0',
	`ccu_sample_count` int DEFAULT 0,
	`ccu_samples` text,
	`chat_count` int DEFAULT 0,
	`valid_chat_count` int DEFAULT 0,
	`chat_score` varchar(32) DEFAULT '0',
	`received_tip_fee` varchar(32) DEFAULT '0',
	`tip_score` varchar(32) DEFAULT '0',
	`featured_post_count` int DEFAULT 0,
	`featured_post_score` varchar(32) DEFAULT '0',
	`total_score` varchar(32) DEFAULT '0',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creator_contributions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `metrics_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` timestamp NOT NULL,
	`phase` varchar(32) NOT NULL,
	`participant_count` int DEFAULT 0,
	`cumulative_participant_count` int DEFAULT 0,
	`stream_duration` int DEFAULT 0,
	`cumulative_stream_duration` int DEFAULT 0,
	`tip_user_count` int DEFAULT 0,
	`tip_amount` varchar(32) DEFAULT '0',
	`cumulative_tip_user_count` int DEFAULT 0,
	`cumulative_tip_amount` varchar(32) DEFAULT '0',
	`post_user_count` int DEFAULT 0,
	`post_count` int DEFAULT 0,
	`featured_post_count` int DEFAULT 0,
	`cumulative_post_user_count` int DEFAULT 0,
	`cumulative_post_count` int DEFAULT 0,
	`cumulative_featured_post_count` int DEFAULT 0,
	`spot_volume` varchar(32) DEFAULT '0',
	`spot_fee` varchar(32) DEFAULT '0',
	`futures_volume` varchar(32) DEFAULT '0',
	`futures_fee` varchar(32) DEFAULT '0',
	`cumulative_spot_volume` varchar(32) DEFAULT '0',
	`cumulative_spot_fee` varchar(32) DEFAULT '0',
	`cumulative_futures_volume` varchar(32) DEFAULT '0',
	`cumulative_futures_fee` varchar(32) DEFAULT '0',
	`bug_count` int DEFAULT 0,
	`cumulative_bug_count` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `metrics_stats_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `points_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`phase` varchar(32) NOT NULL,
	`phase_description` text,
	`total_tokens` varchar(64) NOT NULL,
	`points_pool_percent` varchar(16) NOT NULL,
	`phase_release_percent` varchar(16) NOT NULL,
	`week_count` int NOT NULL,
	`dynamic_pool_percent` varchar(16) NOT NULL,
	`genesis_pool_percent` varchar(16) NOT NULL,
	`p_genesis_percent` varchar(16) NOT NULL,
	`p_eco_percent` varchar(16) NOT NULL,
	`p_trade_percent` varchar(16) NOT NULL,
	`rules_config` text,
	`is_active` int NOT NULL DEFAULT 1,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `points_configs_id` PRIMARY KEY(`id`)
);
